### ISSUE TITLE
Unintended behaviour if one uses the one-liner in README.md

### ISSUE THREAD

**Issue by wh7** [th1nhhdk/lineageos_kernel_builder#1]
First, thanks for providing this script for building LineageOS kernel with KernelSU for Xperia 5 II && 1 II.

I tried to find out why the zips provided in https://github.com/th1nhhdk/android_kernel_sony_sm8250-kernelsu/releases since 2023-07-28 have been unable to activate KernelSU on my Xperia 5 II. After several tries, my finds are as follows.

If I build for `pdx206` directly, then the output zip works fine. But if I use the one-liner provided in README.md
```bash
rm -rf ./build && ./build.sh download_sources && ./build.sh build_kernel && ./build.sh make_anykernel3_zip && mv device_config.sh pdx203_device_config.sh && mv pdx206_device_config.sh device_config.sh && rm -rf build/android_kernel_sony_sm8250/out build/AnyKernel3 && ./build.sh download_sources && ./build.sh build_kernel && ./build.sh make_anykernel3_zip && mv device_config.sh pdx206_device_config.sh && mv pdx203_device_config.sh device_config.sh && rm -rf build/android_kernel_sony_sm8250/out build/AnyKernel3 && ./build.sh download_sources
```
, then the output zip fails to activate KernelSU on my phone.

I found out that the cause is probably the if condition in the function `add_kernelsu()` in `build.sh`
```bash
add_kernelsu() {
    if [ ! -d $workdir/build/$kernel_name/KernelSU ]; then
        cd $workdir/build/$kernel_name
	    	echo "=> Adding KernelSU to kernel source tree..."
	    	curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
	    	echo "=> Configuring kprobe which is needed by KernelSU..."
	    	sed -i -e '/^CONFIG_KPROBES$/d' \
	        	-e '/^CONFIG_HAVE_KPROBES$/d' \
	        	-e '/^CONFIG_KPROBE_EVENTS$/d' \
	        	./arch/$kernel_arch/configs/"$device_name"_defconfig
	    	cat >> ./arch/$kernel_arch/configs/"$device_name"_defconfig << EOF
# Required for KernelSU
CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y
EOF
	    	echo "=> Adding -kernelsu to EXTRAVERSION..."
	    	sed -i 's/\(EXTRAVERSION\s*=\s*\)/\1 -kernelsu/' ./Makefile
	    cd $workdir
    fi
}
```
. If the `$workdir/build/$kernel_name/KernelSU` folder from the building for pdx203 exists, then in the building for pdx206, `./arch/$kernel_arch/configs/"$device_name"_defconfig` won't be altered.

**Comment by th1nhhdk** [comment]
*Oh god, how many faulty pdx206 builds have i published* 

thanks a lot for finding that bug, i'll check it in a bit

**Comment by th1nhhdk** [comment]
I just checked, `2023-08-09` and `2023-08-21` for `pdx206` are broken, and i only have a `pdx203` so i can't test for `pdx206`, i only builds for `pdx206` because they share the same kernel, maybe someone can be a tester?

Also i'm rebuilding with that one liner, it should work

**Comment by th1nhhdk** [comment]
Try [this](https://github.com/th1nhhdk/lineageos_kernel_buildscript/files/12408685/pdx206-4.19.275-kernelsu-perf-2023-08-22-AnyKernel3.zip) build, does it work? @wh7

**Comment by wh7** [comment]
@th1nhhdk It works very well except that the text string for kernel version is now `4.19.275-kernelsu-kernelsu-perf`. I suppose it has something to do with line 65
```
	    sed -i 's/\(EXTRAVERSION\s*=\s*\)/\1 -kernelsu/' ./Makefile
```
in `build.sh`. The consecutive two builds result in something like `EXTRAVERSION =  -kernelsu-kernelsu` in `Makefile`.

**Comment by th1nhhdk** [comment]
> @th1nhhdk It works very well except that the text string for kernel version is now `4.19.275-kernelsu-kernelsu-perf`. I suppose it has something to do with line 65
> 
> ```
> 	    sed -i 's/\(EXTRAVERSION\s*=\s*\)/\1 -kernelsu/' ./Makefile
> ```
> 
> in `build.sh`. The consecutive two builds result in something like `EXTRAVERSION = -kernelsu-kernelsu` in `Makefile`.

I'm a bit busy, i just fixed it with https://github.com/th1nhhdk/lineageos_kernel_buildscript/commit/0796883dda0248675421de98a864b7f7a592fc51

i'll rebuild

**Comment by wh7** [comment]
@th1nhhdk Everything is good. Nice work! I'm gonna close this issue then.
