### ISSUE TITLE
How to use unmerged source?

### ISSUE THREAD

**Issue by huangsijun17** [th1nhhdk/lineageos_kernel_builder#2]
The source code of OnePlus 11 such as the kernel has not been merged and is still in the source code library [OnePlus-11-Development](https://github.com/OnePlus-11-Development). Can I download the source code from the specified address?

**Comment by th1nhhdk** [comment]
> The source code of OnePlus 11 such as the kernel has not been merged and is still in the source code library [OnePlus-11-Development](https://github.com/OnePlus-11-Development). Can I download the source code from the specified address?

Yes, make a fork and i'll help you with it.
